_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "D:/Deeplearning_code/yolov8/detectron2/weight/model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 2000



